/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBankRouteImport } from './routes/app/bank'
import { Route as AppChungtuRouteImport } from './routes/app/chungtu'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppEditorRouteImport } from './routes/app/editor'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppQuotationsRouteImport } from './routes/app/quotations'
import { Route as AppReceivablesRouteImport } from './routes/app/receivables'
import { Route as AppRolesRouteImport } from './routes/app/roles'
import { Route as AppScanRouteImport } from './routes/app/scan'
import { Route as AppSettingsRouteImport } from './routes/app/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppChungtuRoute = AppChungtuRouteImport.update({
  id: '/chungtu',
  path: '/chungtu',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/bank': typeof AppBankRoute
  '/app/chungtu': typeof AppChungtuRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/import': typeof AppImportRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/bank': typeof AppBankRoute
  '/app/chungtu': typeof AppChungtuRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/import': typeof AppImportRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/bank': typeof AppBankRoute
  '/app/chungtu': typeof AppChungtuRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/import': typeof AppImportRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/bank'
    | '/app/chungtu'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/editor'
    | '/app/import'
    | '/app/projects'
    | '/app/quotations'
    | '/app/receivables'
    | '/app/roles'
    | '/app/scan'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/bank'
    | '/app/chungtu'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/editor'
    | '/app/import'
    | '/app/projects'
    | '/app/quotations'
    | '/app/receivables'
    | '/app/roles'
    | '/app/scan'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/bank'
    | '/app/chungtu'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/editor'
    | '/app/import'
    | '/app/projects'
    | '/app/quotations'
    | '/app/receivables'
    | '/app/roles'
    | '/app/scan'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chungtu': {
      id: '/app/chungtu'
      path: '/chungtu'
      fullPath: '/app/chungtu'
      preLoaderRoute: typeof AppChungtuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receivables': {
      id: '/app/receivables'
      path: '/receivables'
      fullPath: '/app/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppChungtuRoute: typeof AppChungtuRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEditorRoute: typeof AppEditorRoute
  AppImportRoute: typeof AppImportRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppRolesRoute: typeof AppRolesRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppChungtuRoute: AppChungtuRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEditorRoute: AppEditorRoute,
  AppImportRoute: AppImportRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppRolesRoute: AppRolesRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
