"use strict";
const NAV_GROUPS=[
 {title:"Điều hành",items:[
  ["dashboard","1","Dashboard điều hành","Tổng quan vận hành"],
  ["my-work","2","Việc của tôi","Nhiệm vụ · SLA · phê duyệt"],
  ["workflow","3","Workflow","Quy trình đang chạy"]]},
 {title:"Nghiệp vụ",items:[
  ["customers","4","Khách hàng","Hồ sơ 360°"],
  ["projects","5","Công trình","Tiến độ · hồ sơ · BOQ"],
  ["quotations","6","Báo giá","Phiên bản · trạng thái"],
  ["documents","7","Kho hồ sơ","Tìm kiếm · tải file"],
  ["receivables","8","Công nợ","Phải thu · quá hạn"]]},
 {title:"Cộng tác",items:[
  ["messages","9","Tin nhắn nội bộ","Chat cá nhân · nhóm"],
  ["settings","10","Tài khoản & cấu hình","Thông tin hệ thống"]]}
];
const META={
 dashboard:["ĐIỀU HÀNH","Dashboard điều hành"],"my-work":["CÔNG VIỆC","Việc của tôi"],workflow:["QUY TRÌNH","Workflow & phê duyệt"],customers:["CRM","Khách hàng"],projects:["CÔNG TRÌNH","Công trình & vòng đời"],quotations:["KINH DOANH","Báo giá"],documents:["HỒ SƠ","Kho tài liệu"],receivables:["TÀI CHÍNH","Theo dõi công nợ"],messages:["CỘNG TÁC","Tin nhắn nội bộ"],settings:["HỆ THỐNG","Tài khoản & cấu hình"]};
const S={me:null,route:"dashboard",loading:false,activeConversation:null,conversations:[],contacts:[],eventSource:null};
const $=(q,r=document)=>r.querySelector(q);const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=v=>Number(v||0).toLocaleString("vi-VN")+" đ";const num=v=>Number(v||0).toLocaleString("vi-VN");
const qs=o=>Object.entries(o||{}).filter(([,v])=>v!==undefined&&v!==null&&v!=="").map(([k,v])=>encodeURIComponent(k)+"="+encodeURIComponent(v)).join("&");
function rowsOf(x){if(Array.isArray(x))return x;if(!x||typeof x!=="object")return[];for(const k of ["rows","items","data","projects","tasks","work_items","notifications","instances","templates"]){if(Array.isArray(x[k]))return x[k]}return[]}
function labelize(k){return String(k).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function toast(msg){const n=document.createElement("div");n.className="toast";n.textContent=msg;$("#toast-root").append(n);setTimeout(()=>n.remove(),3500)}
function setConnection(ok,text){const e=$("#connection-status");e.textContent=text||(ok?"Đã kết nối":"Mất kết nối");e.classList.toggle("offline",!ok)}
async function api(path,{method="GET",body,signal}={}){try{const res=await fetch(path,{method,credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined,signal});const type=res.headers.get("content-type")||"";const data=type.includes("json")?await res.json():await res.text();if(res.status===401){showLogin();throw new Error((data&&data.error)||"Phiên đăng nhập đã hết hạn.")}if(!res.ok)throw new Error((data&&data.error)||`HTTP ${res.status}`);setConnection(true);return data}catch(e){if(e.name!=="AbortError")setConnection(false,"Kết nối lỗi");throw e}}
function renderNav(){const nav=$("#nav");nav.innerHTML=NAV_GROUPS.map(g=>`<div class="nav-group"><div class="nav-group-title">${esc(g.title)}</div>${g.items.map(([id,no,title,sub])=>`<button class="nav-item ${S.route===id?"active":""}" data-route="${id}"><span class="nav-icon">${no}</span><span class="nav-copy"><strong>${esc(title)}</strong><small>${esc(sub)}</small></span></button>`).join("")}</div>`).join("");$$('[data-route]',nav).forEach(b=>b.onclick=()=>{location.hash=b.dataset.route;closeSidebar()})}
function routeFromHash(){const r=(location.hash||"#dashboard").slice(1).split("?")[0];return META[r]?r:"dashboard"}
function showLogin(){S.me=null;stopSSE();$("#app-view").classList.add("hidden");$("#login-view").classList.remove("hidden");setTimeout(()=>$("#login-username")?.focus(),50)}
function showApp(){$("#login-view").classList.add("hidden");$("#app-view").classList.remove("hidden");$("#user-name").textContent=S.me?.full_name||S.me?.username||"";$("#user-role").textContent=S.me?.role||"";renderRoute()}
function openSidebar(){$("#sidebar").classList.add("open");$("#mobile-overlay").classList.remove("hidden")}function closeSidebar(){$("#sidebar").classList.remove("open");$("#mobile-overlay").classList.add("hidden")}
function loading(){return `<div class="loading"><div class="skeleton" style="width:220px;margin:0 auto 12px"></div>Đang tải dữ liệu…</div>`}
function empty(text="Chưa có dữ liệu phù hợp."){return `<div class="empty">${esc(text)}</div>`}
function chip(v){const s=String(v??"");const l=s.toLowerCase();const cls=/hoan|duyet|active|đã|done/.test(l)?"ok":/qua|tre|huy|loi|reject|từ chối/.test(l)?"danger":/cho|pending|draft|moi|mới/.test(l)?"warn":"info";return `<span class="chip ${cls}">${esc(s||"—")}</span>`}
function table(rows,cols,actions=""){if(!rows.length)return empty();return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join("")}${actions?"<th></th>":""}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(([k,,fmt])=>`<td>${fmt?fmt(r[k],r):esc(r[k]??"—")}</td>`).join("")}${actions?`<td>${actions.replaceAll("{id}",esc(r.id))}</td>`:""}</tr>`).join("")}</tbody></table></div>`}
function objectPanel(obj){if(!obj||typeof obj!=="object")return empty();const entries=Object.entries(obj).filter(([,v])=>v===null||["string","number","boolean"].includes(typeof v)).slice(0,40);return `<div class="json-grid">${entries.map(([k,v])=>`<div class="kv"><label>${esc(labelize(k))}</label><div>${esc(v??"—")}</div></div>`).join("")}</div>`}
function openDetail(title,html){const old=$("#detail-panel");if(old)old.remove();const d=document.createElement("aside");d.id="detail-panel";d.className="detail-panel";d.innerHTML=`<div class="detail-head"><strong>${esc(title)}</strong><button id="detail-close" class="icon-btn">×</button></div><div class="detail-body">${html}</div>`;document.body.append(d);$("#detail-close").onclick=()=>d.remove()}
async function loadDetail(endpoint,title){openDetail(title,loading());try{const d=await api(endpoint);$("#detail-panel .detail-body").innerHTML=objectPanel(d)+(rowsOf(d).length?`<div style="margin-top:14px">${table(rowsOf(d),Object.keys(rowsOf(d)[0]||{}).slice(0,6).map(k=>[k,labelize(k)]))}</div>`:"")}catch(e){$("#detail-panel .detail-body").innerHTML=empty(e.message)}}
async function renderRoute(){if(!S.me)return;S.route=routeFromHash();renderNav();const [kick,title]=META[S.route];$("#page-kicker").textContent=kick;$("#page-title").textContent=title;const c=$("#content");c.innerHTML=loading();try{await PAGES[S.route](c)}catch(e){c.innerHTML=`<div class="card"><div class="card-body"><p class="error"><strong>Không tải được dữ liệu.</strong><br>${esc(e.message)}</p><button class="btn secondary" onclick="window.renderRoute()">Thử lại</button></div></div>`}}
const KPI_LABEL={cv_hom_nay:"Việc hôm nay",cv_qua_han:"Việc quá hạn",cv_chua_giao:"Việc chưa giao",bbnt_cho_ky:"BBNT chờ ký",bqt_cho_duyet:"BQT chờ duyệt",tong_cong_ty:"Khách hàng",tong_cong_trinh:"Công trình",gia_tri_du_toan:"Giá trị dự toán",gia_tri_thuc_te:"Giá trị thực tế",cong_no_qua_han:"Công nợ quá hạn",gia_tri_cong_no_qua_han:"Giá trị nợ quá hạn"};
async function pageDashboard(c){const [d,ch]=await Promise.all([api("/api/dashboard"),api("/api/dashboard_charts").catch(()=>({}))]);const k=Object.entries(d.kpi||{}).slice(0,8);const alerts=d.alerts||[];const projects=d.projects||[];const weeks=d.weeks||[];const max=Math.max(...weeks.map(Number),1);c.innerHTML=`<div class="grid kpi">${k.map(([key,v])=>`<article class="card metric"><label>${esc(KPI_LABEL[key]||labelize(key))}</label><strong>${/gia_tri|cong_no/.test(key)?money(v):num(v)}</strong><small>Dữ liệu thời gian thực</small></article>`).join("")}</div><div class="grid two" style="margin-top:14px"><article class="card"><div class="card-head"><h2>Doanh thu 8 tuần</h2></div><div class="card-body">${weeks.length?`<div class="bar-chart">${weeks.map((v,i)=>`<div class="bar-col"><span title="${money(v)}" class="bar" style="height:${Math.max(3,Number(v)/max*170)}px"></span><span class="bar-label">T${i+1}</span></div>`).join("")}</div>`:empty("Vai trò hiện tại không xem dữ liệu doanh thu hoặc chưa có dữ liệu.")}</div></article><article class="card"><div class="card-head"><h2>Cảnh báo điều hành</h2></div><div class="card-body">${alerts.length?alerts.slice(0,10).map(a=>`<div class="alert-row"><strong>${esc(a[0])}</strong><span>${esc(a[1])}</span><span class="muted">${esc(a[2])}</span></div>`).join(""):empty("Không có cảnh báo.")}</div></article></div><article class="card" style="margin-top:14px"><div class="card-head"><h2>Công trình trọng điểm</h2><button class="btn secondary" data-go="projects">Xem tất cả</button></div><div class="card-body">${table(projects,[["code","Mã"],["project_name","Công trình"],["customer_name","Khách hàng"],["status","Trạng thái",chip],["percent_complete","Tiến độ",v=>esc(v??0)+"%"]])}</div></article>`;$("[data-go=projects]")?.addEventListener("click",()=>location.hash="projects")}
async function pageMyWork(c){const [a,b]=await Promise.all([api("/api/my_work_queue").catch(()=>({rows:[]})),api("/api/viec_hom_nay_cua_toi").catch(()=>({rows:[]}))]);const rows=[...rowsOf(a),...rowsOf(b)];c.innerHTML=`<div class="toolbar"><span class="chip info">${rows.length} mục cần xử lý</span><button class="btn secondary" data-go="workflow">Mở workflow</button></div><div class="grid three">${rows.length?rows.slice(0,60).map((r,i)=>`<article class="card"><div class="card-body"><span class="chip ${i<3?"warn":"info"}">${esc(r.kind||r.type||r.trang_thai||r.status||"Công việc")}</span><h3 style="font-size:.9rem">${esc(r.title||r.ten_cong_viec||r.project_name||r.code||"Việc cần xử lý")}</h3><p class="muted" style="font-size:.78rem">${esc(r.next_action||r.mo_ta||r.description||r.customer_name||"")}</p><small>${esc(r.due_at||r.ngay_hen||r.updated_at||"")}</small></div></article>`).join(""):empty()}</div>`;$("[data-go=workflow]")?.addEventListener("click",()=>location.hash="workflow")}
async function pageWorkflow(c){const [r,t]=await Promise.all([api("/api/workflow_resume").catch(()=>({rows:[]})),api("/api/workflow_templates").catch(()=>({rows:[]}))]);const active=rowsOf(r),templates=rowsOf(t);c.innerHTML=`<div class="grid two"><article class="card"><div class="card-head"><h2>Quy trình đang thực hiện</h2></div><div class="card-body">${table(active,[["id","ID"],["template_name","Quy trình"],["project_name","Công trình"],["status","Trạng thái",chip],["current_step","Bước hiện tại"]],`<button class="link-btn wf-detail" data-id="{id}">Chi tiết</button>`)}</div></article><article class="card"><div class="card-head"><h2>Mẫu workflow được phép</h2></div><div class="card-body"><div class="list">${templates.length?templates.map(x=>`<div class="list-item"><strong>${esc(x.name||x.title||x.code)}</strong><small>${esc(x.description||x.mo_ta||x.roles||"")}</small></div>`).join(""):empty()}</div></div></article></div>`;$$('.wf-detail').forEach(b=>b.onclick=()=>loadDetail(`/api/workflow_instance?id=${encodeURIComponent(b.dataset.id)}`,"Chi tiết workflow"))}
async function pageCustomers(c){const d=await api("/api/customers"),rows=rowsOf(d);c.innerHTML=`<div class="toolbar"><input id="customer-filter" class="field" placeholder="Tìm tên, mã số thuế, liên hệ…"><span class="chip info">${rows.length} khách hàng</span></div><div id="customer-table">${renderCustomerTable(rows)}</div>`;const inp=$("#customer-filter");inp.oninput=()=>{const q=inp.value.toLowerCase();$("#customer-table").innerHTML=renderCustomerTable(rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)));bindCustomerDetails()};bindCustomerDetails()}
function renderCustomerTable(rows){return table(rows,[["code","Mã"],["customer_name","Khách hàng"],["phan_loai","Phân loại",chip],["khu_vuc","Khu vực"],["so_tai_lieu","Hồ sơ",num]],`<button class="link-btn customer-detail" data-id="{id}">Hồ sơ 360°</button>`)}function bindCustomerDetails(){$$('.customer-detail').forEach(b=>b.onclick=()=>loadDetail(`/api/customer_360?id=${encodeURIComponent(b.dataset.id)}`,"Hồ sơ khách hàng"))}
async function pageProjects(c){const d=await api("/api/ct_projects"),rows=rowsOf(d);c.innerHTML=`<div class="toolbar"><input id="project-filter" class="field" placeholder="Tìm mã, tên công trình, khách hàng…"><span class="chip info">${rows.length} công trình</span></div><div id="project-table">${renderProjectTable(rows)}</div>`;const inp=$("#project-filter");inp.oninput=()=>{const q=inp.value.toLowerCase();$("#project-table").innerHTML=renderProjectTable(rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)));bindProjectDetails()};bindProjectDetails()}
function renderProjectTable(rows){return table(rows,[["code","Mã"],["project_name","Công trình"],["customer_name","Khách hàng"],["status","Trạng thái",chip],["percent_complete","Tiến độ",v=>esc(v??0)+"%"],["next_action","Bước tiếp"]],`<button class="link-btn project-detail" data-id="{id}">Mở</button>`)}function bindProjectDetails(){$$('.project-detail').forEach(b=>b.onclick=()=>loadDetail(`/api/ct_tong_quan?project_id=${encodeURIComponent(b.dataset.id)}`,"Tổng quan công trình"))}
async function pageQuotations(c){const d=await api("/api/quotations"),rows=rowsOf(d);c.innerHTML=`<div class="toolbar"><span class="chip info">${rows.length} báo giá</span><a class="btn secondary" href="/legacy/index.html#quotation">Soạn báo giá trong giao diện đầy đủ</a></div>${table(rows,[["code","Số BG"],["customer_name","Khách hàng"],["project_name","Công trình"],["version","Phiên bản"],["status","Trạng thái",chip],["grand_total","Tổng tiền",money]],`<button class="link-btn quotation-detail" data-id="{id}">Chi tiết</button>`)}`;$$('.quotation-detail').forEach(b=>b.onclick=()=>loadDetail(`/api/quotation?id=${encodeURIComponent(b.dataset.id)}`,"Chi tiết báo giá"))}
async function pageDocuments(c){async function load(){const q=$("#doc-q")?.value||"",type=$("#doc-type")?.value||"";const d=await api(`/api/documents?${qs({q,type})}`),rows=rowsOf(d);$("#doc-results").innerHTML=table(rows,[["file_name","Tên file"],["doc_type","Loại",chip],["customer_name","Khách hàng"],["project_name","Công trình"],["file_date","Ngày"],["confidentiality","Bảo mật",chip]],`<a class="link-btn" href="/api/document_download?source_document_id={id}">Tải</a>`) }c.innerHTML=`<div class="toolbar"><input id="doc-q" class="field" placeholder="Tìm tên file, khách hàng…"><select id="doc-type" class="field" style="max-width:220px"><option value="">Tất cả loại</option><option>Bao gia</option><option>Hop dong</option><option>BBNT</option><option>BQT</option><option>Hoa don</option><option>Ho so</option><option>Ban ve</option></select><button id="doc-search" class="btn primary">Tìm kiếm</button><a class="btn secondary" href="/legacy/index.html#documents">Quét / mở folder</a></div><div id="doc-results">${loading()}</div>`;$("#doc-search").onclick=load;$("#doc-q").onkeydown=e=>{if(e.key==="Enter")load()};await load()}
async function pageReceivables(c){const d=await api("/api/receivable"),rows=rowsOf(d);const total=rows.reduce((s,r)=>s+Number(r.con_lai??r.remaining??0),0);c.innerHTML=`<div class="grid kpi"><article class="card metric"><label>Tổng còn phải thu</label><strong>${money(total)}</strong><small>Theo quyền tài chính hiện tại</small></article><article class="card metric"><label>Số khoản theo dõi</label><strong>${num(rows.length)}</strong><small>Hóa đơn / hợp đồng</small></article></div><article class="card" style="margin-top:14px"><div class="card-head"><h2>Danh sách công nợ</h2><a class="btn secondary" href="/legacy/index.html#receivable">Nghiệp vụ thu / nhắc nợ</a></div><div class="card-body">${table(rows,[["customer_name","Khách hàng"],["ma_hd","Chứng từ"],["han_thanh_toan","Hạn"],["tong_cong","Tổng",money],["da_thu","Đã thu",money],["con_lai","Còn lại",money],["trang_thai","Trạng thái",chip]])}</div></article>`}
async function pageMessages(c){c.innerHTML=`<div class="chat-layout"><section id="chat-list" class="chat-list"><div class="chat-list-head"><strong>Hội thoại</strong><button id="new-chat" class="btn secondary" style="float:right;padding:5px 8px">Tin mới</button></div><div id="conversations">${loading()}</div></section><section id="chat-pane" class="chat-pane hide-mobile"><div id="chat-title" class="chat-title">Chọn một hội thoại</div><div id="messages" class="messages">${empty("Chọn hội thoại bên trái.")}</div><form id="composer" class="composer"><textarea id="message-input" class="field" placeholder="Nhập tin nhắn…" disabled></textarea><button class="btn primary" disabled>Gửi</button></form></section></div>`;await refreshConversations();$("#new-chat").onclick=newDirectChat;$("#composer").onsubmit=sendChat;startSSE()}
async function refreshConversations(){const d=await api("/api/chat/conversations");S.conversations=rowsOf(d);const box=$("#conversations");if(!box)return;box.innerHTML=S.conversations.length?S.conversations.map(x=>`<button class="conversation ${String(S.activeConversation)===String(x.id)?"active":""}" data-cid="${esc(x.id)}"><span class="unread ${Number(x.unread||0)?"":"hidden"}">${num(x.unread||0)}</span><strong>${esc(x.display_name||x.title||"Hội thoại")}</strong><small>${esc(x.last_body||"Chưa có tin nhắn")}</small></button>`).join(""):empty("Chưa có hội thoại.");$$('.conversation',box).forEach(b=>b.onclick=()=>openConversation(b.dataset.cid))}
async function openConversation(id){S.activeConversation=id;await refreshConversations();const conv=S.conversations.find(x=>String(x.id)===String(id));$("#chat-title").textContent=conv?.display_name||conv?.title||"Hội thoại";$("#chat-pane").classList.remove("hide-mobile");$("#chat-list").classList.add("hide-mobile");const d=await api(`/api/chat/messages?${qs({conversation_id:id,limit:80})}`);renderMessages(rowsOf(d));const last=rowsOf(d).at(-1)?.id;if(last)api("/api/chat/read",{method:"POST",body:{conversation_id:Number(id),up_to_message_id:last}}).catch(()=>{});$("#message-input").disabled=false;$("#composer button").disabled=false;$("#message-input").focus()}
function renderMessages(rows){const box=$("#messages");if(!box)return;box.innerHTML=rows.length?rows.map(m=>`<article class="message ${String(m.sender_id)===String(S.me?.user_id||S.me?.id)?"mine":""}"><small>${esc(m.sender_name||m.sender_username||"")} · ${esc(m.created_at||"")}</small><p>${esc(m.body||"")}</p>${(m.attachments||[]).map(a=>`<a href="/api/chat/attachment?id=${encodeURIComponent(a.id)}">📎 ${esc(a.file_name)}</a>`).join("")}</article>`).join(""):empty("Chưa có tin nhắn.");box.scrollTop=box.scrollHeight}
async function sendChat(e){e.preventDefault();const input=$("#message-input"),body=input.value.trim();if(!body||!S.activeConversation)return;input.disabled=true;try{await api("/api/chat/send",{method:"POST",body:{conversation_id:Number(S.activeConversation),body}});input.value="";await openConversation(S.activeConversation)}catch(err){toast(err.message)}finally{input.disabled=false;input.focus()}}
async function newDirectChat(){try{if(!S.contacts.length)S.contacts=rowsOf(await api("/api/chat/contacts"));const opts=S.contacts.map(x=>`${x.id}: ${x.full_name||x.username}`).join("\n");const raw=prompt("Nhập ID người nhận:\n"+opts);if(!raw)return;const userId=parseInt(raw,10);if(!userId)throw new Error("ID không hợp lệ.");const d=await api("/api/chat/direct",{method:"POST",body:{user_id:userId}});await refreshConversations();await openConversation(d.conversation_id)}catch(e){toast(e.message)}}
function startSSE(){if(S.eventSource)return;try{const es=new EventSource("/api/chat/stream");S.eventSource=es;es.addEventListener("message",()=>{refreshConversations().catch(()=>{});if(S.activeConversation)openConversation(S.activeConversation).catch(()=>{})});es.addEventListener("chat_message",()=>{refreshConversations().catch(()=>{});if(S.activeConversation)openConversation(S.activeConversation).catch(()=>{})});es.addEventListener("hb",()=>setConnection(true,"Realtime online"));es.onerror=()=>setConnection(false,"Realtime đang nối lại") }catch{}}
function stopSSE(){if(S.eventSource){S.eventSource.close();S.eventSource=null}}
async function pageSettings(c){const cfg=await api("/api/cau_hinh_tong_hop").catch(()=>({}));const dens=localStorage.getItem("th-modern-density")||"compact";const hc=localStorage.getItem("th-modern-hc")==="1";c.innerHTML=`<div class="grid two"><article class="card"><div class="card-head"><h2>Tài khoản hiện tại</h2></div><div class="card-body">${objectPanel(S.me)}</div></article><article class="card"><div class="card-head"><h2>Cấu hình hệ thống</h2></div><div class="card-body">${objectPanel(cfg)}</div></article></div><article class="card" style="margin-top:14px"><div class="card-head"><h2>Trải nghiệm giao diện</h2></div><div class="card-body"><div class="toolbar"><label class="chip info"><input type="checkbox" id="pref-hc" ${hc?"checked":""}> Tăng độ tương phản</label><select id="pref-density" class="field" style="max-width:180px"><option value="compact" ${dens==="compact"?"selected":""}>Mật độ gọn</option><option value="comfortable" ${dens==="comfortable"?"selected":""}>Mật độ thoáng</option></select></div><p class="muted" style="font-size:.78rem;margin:0">Token brand chuẩn #0B7285 · mật độ bảng &amp; tương phản lưu trên trình duyệt này.</p></div></article><article class="card" style="margin-top:14px"><div class="card-head"><h2>Chế độ tương thích</h2></div><div class="card-body"><p class="muted">Giao diện mới tập trung vào tra cứu và điều hành. Những nghiệp vụ chuyên sâu chưa port đầy đủ vẫn mở an toàn trong giao diện hiện hữu, dùng cùng phiên đăng nhập và cùng API.</p><a class="btn primary" href="/legacy/index.html">Mở giao diện đầy đủ cũ</a></div></article>`;$("#pref-hc").onchange=e=>{localStorage.setItem("th-modern-hc",e.target.checked?"1":"0");applyUxPrefs()};$("#pref-density").onchange=e=>{localStorage.setItem("th-modern-density",e.target.value);applyUxPrefs()}}
function applyUxPrefs(){const dens=localStorage.getItem("th-modern-density")||"compact";const hc=localStorage.getItem("th-modern-hc")==="1";document.documentElement.dataset.density=dens;document.documentElement.dataset.highContrast=hc?"true":"false"}
const PAGES={dashboard:pageDashboard,"my-work":pageMyWork,workflow:pageWorkflow,customers:pageCustomers,projects:pageProjects,quotations:pageQuotations,documents:pageDocuments,receivables:pageReceivables,messages:pageMessages,settings:pageSettings};
async function bootstrap(){applyUxPrefs();renderNav();try{const d=await api("/api/me");if(d.authenticated){S.me=d.user;showApp()}else showLogin()}catch{showLogin()}}
$("#login-form").onsubmit=async e=>{e.preventDefault();const err=$("#login-error");err.textContent="";const btn=e.currentTarget.querySelector("button");btn.disabled=true;try{const d=await api("/api/login",{method:"POST",body:{username:$("#login-username").value.trim(),password:$("#login-password").value}});S.me=d.user||{username:$("#login-username").value,full_name:d.full_name,role:d.role};if(S.me.must_change||d.must_change){toast("Tài khoản cần đổi mật khẩu. Hãy mở giao diện đầy đủ cũ để đổi mật khẩu.")}showApp()}catch(ex){err.textContent=ex.message}finally{btn.disabled=false}};
$("#logout-btn").onclick=async()=>{try{await api("/api/logout",{method:"POST",body:{}})}catch{}stopSSE();showLogin()};$("#refresh-btn").onclick=()=>renderRoute();$("#menu-btn").onclick=openSidebar;$("#sidebar-close").onclick=closeSidebar;$("#mobile-overlay").onclick=closeSidebar;window.addEventListener("hashchange",renderRoute);window.renderRoute=renderRoute;bootstrap();
